### ISSUE TITLE
[SWMEBPlus] Determining current instance

### ISSUE THREAD

**Issue by foxriver76** [yhwang1990/SW-MEB#1]
I came across a problem, that the oldest instance is always used also when outdated. When looking at the code, the checks https://github.com/yhwang1990/SW-MEB/blob/c75ae02f1cd5b5ba1b724b8b9ece14276477552e/src/sw_meb/KernelSWMEB_Plus.java#L98 etc seem to be wrong.

Shouldn't you check here it the instance at the oldest ball is outdated via 

```java
if (index.get(0) <= cur_id - Util.W + 1) {
```

**Comment by yhwang1990** [comment]
Hi Max,

I have double-checked the code. I think you are correct and it should be "if (index.get(0) < cur_id - Util.W + 1)" here and any other position using this condition.

I will fix all the bugs in the code. Thank you so much for pointing out it.

**Comment by foxriver76** [comment]
Thanks for your fast response and for validating my assumption.
